### ISSUE TITLE
arguments option issue

### ISSUE THREAD

**Issue by victorlcm** [k6io/operator#11]
Hey guys, first of all thank you so much for your work!

I'm trying to execute the operator with the following spec:

```yaml
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script: aligator-stress-test
  arguments: --out kafka=brokers=dockerhost:9092,topic=load-output,format=json
```

however, when running the `apply` I'm getting the error 

`time="2021-04-23T20:02:25Z" level=error msg="unknown flag: --out kafka"`

Could anyone help me out with this issue?
